import { requireSession } from '../auth/guard.js';
import { renderShell } from '../shared/layout.js';
import { api } from '../api/client.js';
import { emptyState, escapeHtml, formatMoney, showToast, withButtonLoading, toMinorUnits } from '../shared/ui.js';
const session = await requireSession(); renderShell(session, 'invoices.html');
const branchSelect = document.getElementById('invoice-branch'); const list = document.getElementById('invoice-list');
async function load() { list.innerHTML = '<div class="empty-state">Loading invoices…</div>'; try { const result = await api.get('/invoices', { page: 1, limit: 20 }); if (!result.data.length) { emptyState(list, { title: 'No invoices yet', message: 'Create an invoice when a customer needs a formal payment record.' }); return; } list.innerHTML = `<div class="table-wrap"><table><thead><tr><th>Number</th><th>Total</th><th>Status</th><th>Created</th></tr></thead><tbody>${result.data.map((invoice) => `<tr><td>${escapeHtml(invoice.invoiceNumber)}</td><td>${formatMoney(invoice.totalMinor, session.business.currency)}</td><td><span class="badge badge-muted">${escapeHtml(invoice.status)}</span></td><td>${escapeHtml(new Date(invoice.createdAt).toLocaleDateString())}</td></tr>`).join('')}</tbody></table></div>`; } catch (error) { list.innerHTML = '<div class="empty-state"><h3>Invoices unavailable</h3><p>Try again in a moment.</p></div>'; showToast(error.message, 'error'); } }
try { const branches = await api.get('/branches'); branchSelect.innerHTML = branches.data.map((branch) => `<option value="${branch._id}">${escapeHtml(branch.name)}</option>`).join(''); await load(); } catch (error) { showToast(error.message, 'error'); }
document.getElementById('invoice-form').addEventListener('submit', async (event) => { event.preventDefault(); await withButtonLoading(document.getElementById('invoice-submit'), 'Creating…', async () => { try { await api.post('/invoices', { branchId: branchSelect.value, lines: [{ description: document.getElementById('invoice-description').value.trim(), quantity: Number(document.getElementById('invoice-quantity').value), unitPriceMinor: toMinorUnits(document.getElementById('invoice-price').value) }], notes: document.getElementById('invoice-notes').value.trim(), status: 'ISSUED' }); event.target.reset(); showToast('Invoice created.', 'success'); await load(); } catch (error) { showToast(error.message, 'error'); } }); });
document.getElementById('refresh-invoices').addEventListener('click', load);
