const express = require('express');
const authenticate = require('../middleware/authenticate');
const resolveTenant = require('../middleware/resolveTenant');
const requirePermission = require('../middleware/requirePermission');
const { PERMISSIONS } = require('../config/permissions');
const controller = require('../controllers/staffController');
const router = express.Router();
router.use(authenticate, resolveTenant);
router.get('/', requirePermission(PERMISSIONS.STAFF_VIEW), controller.list);
router.post('/', requirePermission(PERMISSIONS.STAFF_MANAGE), controller.create);
router.patch('/:id', requirePermission(PERMISSIONS.STAFF_MANAGE), controller.update);
module.exports = router;
