import { requireSession } from '../auth/guard.js';
import { renderShell } from '../shared/layout.js';
import { api } from '../api/client.js';
import { emptyState, escapeHtml, showToast, withButtonLoading } from '../shared/ui.js';
const session = await requireSession(); renderShell(session, 'staff.html');
const list = document.getElementById('staff-list'); const branch = document.getElementById('staff-branch');
async function load() { list.innerHTML = '<div class="empty-state">Loading team…</div>'; try { const result = await api.get('/staff'); if (!result.data.length) { emptyState(list, { title: 'No staff yet', message: 'Add your first team member and assign their role.' }); return; } list.innerHTML = `<div class="table-wrap"><table><thead><tr><th>Name</th><th>Role</th><th>Branch</th><th>Status</th></tr></thead><tbody>${result.data.map((member) => `<tr><td>${escapeHtml(member.user?.fullName || '')}<br><small class="topbar-meta">${escapeHtml(member.user?.email || '')}</small></td><td>${escapeHtml(member.role?.name || '')}</td><td>${escapeHtml(member.branch?.name || 'All branches')}</td><td><span class="badge ${member.status === 'ACTIVE' ? 'badge-success' : 'badge-muted'}">${escapeHtml(member.status)}</span></td></tr>`).join('')}</tbody></table></div>`; } catch (error) { list.innerHTML = '<div class="empty-state"><h3>Team unavailable</h3><p>Try again in a moment.</p></div>'; showToast(error.message, 'error'); } }
try { const branches = await api.get('/branches'); branch.innerHTML = branches.data.map((item) => `<option value="${item._id}">${escapeHtml(item.name)}</option>`).join(''); await load(); } catch (error) { showToast(error.message, 'error'); }
document.getElementById('staff-form').addEventListener('submit', async (event) => { event.preventDefault(); await withButtonLoading(document.getElementById('staff-submit'), 'Adding…', async () => { try { await api.post('/staff', { fullName: document.getElementById('staff-name').value.trim(), email: document.getElementById('staff-email').value.trim(), password: document.getElementById('staff-password').value, roleName: document.getElementById('staff-role').value, branchId: branch.value }); event.target.reset(); showToast('Staff member added.', 'success'); await load(); } catch (error) { showToast(error.message, 'error'); } }); });
document.getElementById('refresh-staff').addEventListener('click', load);
